=== mightyelf13/Data-formats/FixingHW3/FixingHW3/3/xml/schemas/schema-3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://example.com/schema-3"
           xmlns="http://example.com/schema-3"
           xmlns:xml="http://www.w3.org/XML/1998/namespace"
           elementFormDefault="qualified">

    <xs:import namespace="http://www.w3.org/XML/1998/namespace" 
               schemaLocation="http://www.w3.org/2001/xml.xsd"/>

    <xs:complexType name="LocalizableString">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute ref="xml:lang" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:element name="CinemasAndCountries">
        <xs:complexType>
            <xs:all>
                <xs:element ref="Countries"/>
                <xs:element ref="Cinemas"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="Countries">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Country" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Country">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Name" type="LocalizableString" maxOccurs="unbounded"/>
                <xs:element name="Code" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Cinemas">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Cinema" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Cinema">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Name" type="LocalizableString" maxOccurs="unbounded"/>
                <xs:element name="Capacity" type="xs:int"/>
                <xs:element name="Luxury" type="xs:boolean"/>
                <xs:element name="Phone" type="xs:string" maxOccurs="unbounded" minOccurs="0"/>
                <xs:element name="Location" type="CountryRefType"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="CountryRefType">
        <xs:attribute name="ref" type="xs:IDREF" use="required"/>
    </xs:complexType>

</xs:schema>

=== mightyelf13/Data-formats/DataFormatsAssignments-main/xml/data/data-3.xml
<?xml version="1.0" encoding="UTF-8"?>
<CinemasAndCountries xmlns="http://example.com/movies"
                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:schemaLocation="http://example.com/movies ../schemas/schema-3.xsd">
    <Countries>
        <Country id="country_us">
            <Name xml:lang="en">United States</Name>
            <Code>US</Code>
        </Country>
        <Country id="country_uk">
            <Name xml:lang="en">United Kingdom</Name>
            <Code>GB</Code>
        </Country>
        <Country id="country_fr">
            <Name xml:lang="en">France</Name>
            <Code>FR</Code>
        </Country>
    </Countries>
    
    <Cinemas>
        <Cinema id="cinema_imax-london">
            <Name xml:lang="en">IMAX London</Name>
            <Capacity>500</Capacity>
            <Luxury>true</Luxury>
            <Phone>+441234567890</Phone>
            <Phone>+442345678901</Phone>
            <Location ref="country_uk"/>
        </Cinema>

        <Cinema id="cinema_amc-la">
            <Name xml:lang="en">AMC Los Angeles</Name>
            <Capacity>350</Capacity>
            <Luxury>false</Luxury>
            <Location ref="country_us"/>
        </Cinema>

        <Cinema id="cinema_le-grand-paris">
            <Name xml:lang="en">Le Grand Paris</Name>
            <Capacity>220</Capacity>
            <Luxury>true</Luxury>
            <Phone>+330987654321</Phone>
            <Location ref="country_fr"/>
        </Cinema>
    </Cinemas>

                    
</CinemasAndCountries>
