=== mightyelf13/Data-formats/NPRG036-T1G6-HW3/3/xml/schemas/schema-1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://example.com/movies"
           xmlns="http://example.com/movies"
           xmlns:xml="http://www.w3.org/XML/1998/namespace"
           elementFormDefault="qualified">

    <xs:import namespace="http://www.w3.org/XML/1998/namespace" 
               schemaLocation="http://www.w3.org/2001/xml.xsd"/>

    <xs:complexType name="LocalizableString">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute ref="xml:lang" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:element name="MovieDatabase">
        <xs:complexType>
            <xs:all>
                <xs:element ref="Countries"/>
                <xs:element ref="Studios"/>
                <xs:element ref="Cinemas"/>
                <xs:element ref="People"/>
                <xs:element ref="Movies"/>
                <xs:element ref="Screenings"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="Countries">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Country" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Country">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Name" type="LocalizableString" maxOccurs="unbounded"/>
                <xs:element name="Code" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Studios">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Studio" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Studio">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Name" type="LocalizableString" maxOccurs="unbounded"/>
                <xs:element name="FoundedYear" type="xs:gYear"/>
                <xs:element name="MoviesProduced" type="xs:integer"/>
                <xs:element name="Location" type="CountryRefType"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Cinemas">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Cinema" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Cinema">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Name" type="LocalizableString" maxOccurs="unbounded"/>
                <xs:element name="Capacity" type="xs:integer"/>
                <xs:element name="Luxury" type="xs:boolean"/>
                <xs:element name="Phone" type="xs:string" maxOccurs="unbounded" minOccurs="0"/>
                <xs:element name="Location" type="CountryRefType"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="People">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Person" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Person">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="FullName" type="LocalizableString" maxOccurs="unbounded"/>
                <xs:element name="BirthDate" type="xs:date"/>
                <xs:element name="ActiveSince" type="xs:gYear" minOccurs="0"/>
                <xs:element name="AwardsCount" type="xs:integer" minOccurs="0"/>
                <xs:element name="StageName" type="LocalizableString" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="DebutYear" type="xs:gYear" minOccurs="0"/>
                <xs:element name="BornIn" type="CountryRefType" minOccurs="0"/>
                <xs:element name="ActedIn" type="MovieRefType" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
            <xs:attribute name="type" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Director"/>
                        <xs:enumeration value="Actor"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="Movies">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Movie" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Movie">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Title" type="LocalizableString" maxOccurs="unbounded"/>
                <xs:element name="Duration" type="xs:integer"/>
                <xs:element name="ReleaseDate" type="xs:date"/>
                <xs:element name="DirectedBy" type="PersonRefType"/>
                <xs:element name="ProducedBy" type="StudioRefType"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Screenings">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Screening" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Screening">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Date" type="xs:date"/>
                <xs:element name="Time" type="xs:time"/>
                <xs:element name="Language" type="xs:language"/>
                <xs:element name="Shows" type="MovieRefType"/>
                <xs:element name="TakesPlaceAt" type="CinemaRefType"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="CountryRefType">
        <xs:attribute name="ref" type="xs:IDREF" use="required"/>
    </xs:complexType>

    <xs:complexType name="StudioRefType">
        <xs:attribute name="ref" type="xs:IDREF" use="required"/>
    </xs:complexType>

    <xs:complexType name="CinemaRefType">
        <xs:attribute name="ref" type="xs:IDREF" use="required"/>
    </xs:complexType>

    <xs:complexType name="PersonRefType">
        <xs:attribute name="ref" type="xs:IDREF" use="required"/>
    </xs:complexType>

    <xs:complexType name="MovieRefType">
        <xs:attribute name="ref" type="xs:IDREF" use="required"/>
    </xs:complexType>

</xs:schema>

=== mightyelf13/Data-formats/NPRG036-T1G6-HW3/3/xml/data/data-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<MovieDatabase xmlns="http://example.com/movies"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://example.com/movies ../schemas/schema-1.xsd">
    
    <Countries>
        <Country id="country_us">
            <Name xml:lang="en">United States</Name>
            <Code>US</Code>
        </Country>
        <Country id="country_uk">
            <Name xml:lang="en">United Kingdom</Name>
            <Code>GB</Code>
        </Country>
        <Country id="country_fr">
            <Name xml:lang="en">France</Name>
            <Code>FR</Code>
        </Country>
    </Countries>

    <Studios>
        <Studio id="studio_warner-bros">
            <Name xml:lang="en">Warner Bros. Pictures</Name>
            <FoundedYear>1923</FoundedYear>
            <MoviesProduced>12500</MoviesProduced>
            <Location ref="country_us"/>
        </Studio>

        <Studio id="studio_universal">
            <Name xml:lang="en">Universal Pictures</Name>
            <FoundedYear>1912</FoundedYear>
            <MoviesProduced>400</MoviesProduced>
            <Location ref="country_us"/>
        </Studio>

        <Studio id="studio_legendary">
            <Name xml:lang="en">Legendary Pictures</Name>
            <FoundedYear>2000</FoundedYear>
            <MoviesProduced>70</MoviesProduced>
            <Location ref="country_us"/>
        </Studio>
    </Studios>

    <Cinemas>
        <Cinema id="cinema_imax-london">
            <Name xml:lang="en">IMAX London</Name>
            <Capacity>500</Capacity>
            <Luxury>true</Luxury>
            <Phone>+441234567890</Phone>
            <Phone>+442345678901</Phone>
            <Location ref="country_uk"/>
        </Cinema>

        <Cinema id="cinema_amc-la">
            <Name xml:lang="en">AMC Los Angeles</Name>
            <Capacity>350</Capacity>
            <Luxury>false</Luxury>
            <Location ref="country_us"/>
        </Cinema>

        <Cinema id="cinema_le-grand-paris">
            <Name xml:lang="en">Le Grand Paris</Name>
            <Capacity>220</Capacity>
            <Luxury>true</Luxury>
            <Phone>+330987654321</Phone>
            <Location ref="country_fr"/>
        </Cinema>
    </Cinemas>

    <People>
        <Person id="person_christopher-nolan" type="Director">
            <FullName xml:lang="en">Christopher Nolan</FullName>
            <BirthDate>1970-07-30</BirthDate>
            <ActiveSince>1998</ActiveSince>
            <AwardsCount>220</AwardsCount>
            <BornIn ref="country_uk"/>
        </Person>

        <Person id="person_denis-villeneuve" type="Director">
            <FullName xml:lang="en">Denis Villeneuve</FullName>
            <BirthDate>1967-10-03</BirthDate>
            <ActiveSince>1994</ActiveSince>
            <AwardsCount>160</AwardsCount>
            <BornIn ref="country_fr"/>
        </Person>

        <Person id="person_patty-jenkins" type="Director">
            <FullName xml:lang="en">Patty Jenkins</FullName>
            <BirthDate>1971-07-24</BirthDate>
            <ActiveSince>2003</ActiveSince>
            <AwardsCount>40</AwardsCount>
            <BornIn ref="country_us"/>
        </Person>

        <Person id="person_leonardo-dicaprio" type="Actor">
            <FullName xml:lang="en">Leonardo DiCaprio</FullName>
            <BirthDate>1974-11-11</BirthDate>
            <StageName xml:lang="en">Leonardo DiCaprio</StageName>
            <DebutYear>1991</DebutYear>
            <BornIn ref="country_us"/>
            <ActedIn ref="movie_inception"/>
        </Person>

        <Person id="person_amy-adams" type="Actor">
            <FullName xml:lang="en">Amy Adams</FullName>
            <BirthDate>1974-08-20</BirthDate>
            <StageName xml:lang="en">Amy Adams</StageName>
            <DebutYear>1995</DebutYear>
            <BornIn ref="country_us"/>
            <ActedIn ref="movie_arrival"/>
            <ActedIn ref="movie_inception"/>
        </Person>

        <Person id="person_gal-gadot" type="Actor">
            <FullName xml:lang="en">Gal Gadot</FullName>
            <BirthDate>1985-04-30</BirthDate>
            <StageName xml:lang="en">Gal Gadot</StageName>
            <DebutYear>2007</DebutYear>
            <BornIn ref="country_us"/>
            <ActedIn ref="movie_wonder-woman"/>
            <ActedIn ref="movie_arrival"/>
        </Person>
    </People>

    <Movies>
        <Movie id="movie_inception">
            <Title xml:lang="en">Inception</Title>
            <Duration>148</Duration>
            <ReleaseDate>2010-07-16</ReleaseDate>
            <DirectedBy ref="person_christopher-nolan"/>
            <ProducedBy ref="studio_warner-bros"/>
        </Movie>

        <Movie id="movie_arrival">
            <Title xml:lang="en">Arrival</Title>
            <Duration>116</Duration>
            <ReleaseDate>2016-11-11</ReleaseDate>
            <DirectedBy ref="person_denis-villeneuve"/>
            <ProducedBy ref="studio_legendary"/>
        </Movie>

        <Movie id="movie_wonder-woman">
            <Title xml:lang="en">Wonder Woman</Title>
            <Duration>141</Duration>
            <ReleaseDate>2017-06-02</ReleaseDate>
            <DirectedBy ref="person_patty-jenkins"/>
            <ProducedBy ref="studio_warner-bros"/>
        </Movie>
    </Movies>

    <Screenings>
        <Screening id="screening_inc-lon-2024-06-01-2000">
            <Date>2024-06-01</Date>
            <Time>20:00:00</Time>
            <Language>en</Language>
            <Shows ref="movie_inception"/>
            <TakesPlaceAt ref="cinema_imax-london"/>
        </Screening>

        <Screening id="screening_arr-la-2024-06-02-1800">
            <Date>2024-06-02</Date>
            <Time>18:00:00</Time>
            <Language>en</Language>
            <Shows ref="movie_arrival"/>
            <TakesPlaceAt ref="cinema_amc-la"/>
        </Screening>

        <Screening id="screening_ww-par-2024-06-03-1900">
            <Date>2024-06-03</Date>
            <Time>19:00:00</Time>
            <Language>fr</Language>
            <Shows ref="movie_wonder-woman"/>
            <TakesPlaceAt ref="cinema_le-grand-paris"/>
        </Screening>
    </Screenings>

</MovieDatabase>
