=== mightyelf13/Data-formats/NPRG036-T1G6-HW3/3/xml/schemas/schema-4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://example.com/movies"
           xmlns="http://example.com/movies"
           xmlns:xml="http://www.w3.org/XML/1998/namespace"
           elementFormDefault="qualified">

    <xs:import namespace="http://www.w3.org/XML/1998/namespace" 
               schemaLocation="http://www.w3.org/2001/xml.xsd"/>

    <xs:complexType name="LocalizableString">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute ref="xml:lang" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:element name="StudiosAndCountries">
        <xs:complexType>
            <xs:all>
                <xs:element ref="Countries"/>
                <xs:element ref="Studios"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="Countries">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Country" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Country">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Name" type="LocalizableString" maxOccurs="unbounded"/>
                <xs:element name="Code" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Studios">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Studio" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Studio">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Name" type="LocalizableString" maxOccurs="unbounded"/>
                <xs:element name="FoundedYear" type="xs:gYear"/>
                <xs:element name="MoviesProduced" type="xs:int"/>
                <xs:element name="Location" type="CountryRefType"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="CountryRefType">
        <xs:attribute name="ref" type="xs:IDREF" use="required"/>
    </xs:complexType>

</xs:schema>

=== mightyelf13/Data-formats/DataFormatsAssignments-main/xml/data/data-4.xml
<?xml version="1.0" encoding="UTF-8"?>
<StudiosAndCountries xmlns="http://example.com/movies"
                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:schemaLocation="http://example.com/movies ../schemas/schema-4.xsd">
    <Countries>
        <Country id="country_us">
            <Name xml:lang="en">United States</Name>
            <Code>US</Code>
        </Country>
        <Country id="country_uk">
            <Name xml:lang="en">United Kingdom</Name>
            <Code>GB</Code>
        </Country>
        <Country id="country_fr">
            <Name xml:lang="en">France</Name>
            <Code>FR</Code>
        </Country>
    </Countries>

    <Studios>
        <Studio id="studio_warner-bros">
            <Name xml:lang="en">Warner Bros. Pictures</Name>
            <FoundedYear>1923</FoundedYear>
            <MoviesProduced>12500</MoviesProduced>
            <Location ref="country_us"/>
        </Studio>

        <Studio id="studio_universal">
            <Name xml:lang="en">Universal Pictures</Name>
            <FoundedYear>1912</FoundedYear>
            <MoviesProduced>400</MoviesProduced>
            <Location ref="country_us"/>
        </Studio>

        <Studio id="studio_legendary">
            <Name xml:lang="en">Legendary Pictures</Name>
            <FoundedYear>2000</FoundedYear>
            <MoviesProduced>70</MoviesProduced>
            <Location ref="country_us"/>
        </Studio>
    </Studios>

</StudiosAndCountries>
